# docker-compose.yml

version: '3.8'

services:
  web:
    # 使用当前目录下的 Dockerfile 构建镜像
    build:
      context: .
    # 容器名称
    container_name: simple-message-service
    # 端口映射: 宿主机端口:容器端口
    ports:
      - "3000:3000"
    # 移除卷挂载，因为所有的代码和依赖都已在镜像中
    # volumes:
    #   - ./dist:/app
    #   - ./.env.dev:/app/.env.dev
    # 使用 env_file 来加载环境变量，而不是挂载文件
    env_file:
      - ./.env.dev
    # 指定运行环境为 development
    environment:
      - NODE_ENV=development