# deploy/docker-compose.yml

version: '3.8'

services:
  web:
    # 使用新的 Dockerfile 构建镜像
    build:
      # context 必须指向 Dockerfile 所在的目录，即 dist/
      context: .
      # 指定 Dockerfile 的位置
      dockerfile: Dockerfile
    # 容器名称
    container_name: simple-message-service
    # 端口映射: 宿主机端口:容器端口
    ports:
      - "8080:8080"
      - "8081:8081"
    # 使用 env_file 来加载环境变量
    # 由于 .env.prod 文件现在在与 docker-compose.yml 相同的目录，路径也相应简化
    env_file:
      - ./.env.prod
    # 指定运行环境为 production
    environment:
      - NODE_ENV=production